export const OPEN = "OPEN";
export const CLOSED = "CLOSED";

export const INITIAL_WINBOX_STATES = {
  README: OPEN,
  TRASH: CLOSED,
  SOURCES: CLOSED,
  TERMINAL: CLOSED,
  TRANSLATION: CLOSED,
  DIALOGUE: CLOSED,
  ACKNOWLEDGMENTS: CLOSED,
  ERASURE: CLOSED,
  ERASURE1: CLOSED,
  ERASURE2: CLOSED,
};
