export const OPEN = "OPEN";
export const CLOSED = "CLOSED";

export const INITIAL_WINBOX_STATES = {
  README: OPEN,
  TRASH: CLOSED,
  SOURCES: CLOSED,
  TERMINAL: CLOSED,
  TRANSLATE: CLOSED,
  DIALOGUE: CLOSED,
  ERASURE: CLOSED,
  ERASURE1: CLOSED,
};
