export const OPEN = "OPEN";
export const CLOSED = "CLOSED";

export const INITIAL_WINBOX_STATES = {
  README: OPEN,
  TRASH: CLOSED,
  SOURCES: CLOSED,
  TERMINAL: CLOSED,
  "COMMUNICATION PARTNERS": CLOSED,
  TRANSLATION: CLOSED,
  DIALOGUE: CLOSED,
  INSCRIPTION: CLOSED,
  INSPIRATION: CLOSED,
  ACKNOWLEDGMENTS: CLOSED,
  ERASURE: CLOSED,
  ERASURE1: CLOSED,
  ERASURE2: CLOSED,
  "HAL9000.JPG": CLOSED,
  "A HISTORY OF COMMUNICATION": CLOSED,
  "PUNCHCARD.JPG": CLOSED,
  "TELETYPE.JPG": CLOSED,
  "TEKTRONIX.JPG": CLOSED,
};
